services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5001:5001"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped

volumes:
  caddy_data: {}
  caddy_config: {}
